services:
    ttys3.baidutongji.listener:
        class: ttys3\baidutongji\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
